"""blitz fix

Revision ID: 42c79288a86b
Revises: 721230c58753
Create Date: 2025-08-11 23:49:47.697338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '42c79288a86b'
down_revision: Union[str, Sequence[str], None] = '721230c58753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blitz_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('blitz_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('goals_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('count_score', sa.Float(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['blitz_id'], ['blitzs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['blitz_team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('blitz_characters')
    op.add_column('blitzs', sa.Column('cost', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blitzs', 'cost')
    op.create_table('blitz_characters',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('character_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('blitz_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('goals_count', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('count_score', mysql.FLOAT(), server_default=sa.text("'0'"), nullable=False),
    sa.ForeignKeyConstraint(['blitz_id'], ['blitzs.id'], name=op.f('blitz_characters_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('blitz_characters_ibfk_2')),
    sa.ForeignKeyConstraint(['team_id'], ['blitz_team.id'], name=op.f('blitz_characters_ibfk_3'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('blitz_users')
    # ### end Alembic commands ###
