"""add main character

Revision ID: 4e81d65ea4c3
Revises: 6eb29a2b7b20
Create Date: 2025-08-09 23:49:36.555320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e81d65ea4c3'
down_revision: Union[str, Sequence[str], None] = '6eb29a2b7b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('main_character_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'characters', ['main_character_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'main_character_id')
    # ### end Alembic commands ###
