"""initial tables

Revision ID: 6eb29a2b7b20
Revises: 
Create Date: 2025-08-09 23:47:43.004075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb29a2b7b20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blitz_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blitzs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('blitz_type', sa.Enum('VIP_BLITZ_V8', 'BLITZ_V8', 'BLITZ_V16', 'BLITZ_V32', 'BLITZ_V64', name='blitztype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('T_SHIRT', 'SHORTS', 'GAITERS', 'BOOTS', name='itemcategory'), nullable=True),
    sa.Column('level_required', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('stats', sa.String(length=255), nullable=True),
    sa.Column('owner_character_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.create_table('training_timer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_timer_id'), 'training_timer', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_full_name', sa.String(length=255), nullable=True),
    sa.Column('user_time_register', sa.DateTime(), nullable=True),
    sa.Column('money', sa.BigInteger(), nullable=True),
    sa.Column('energy', sa.BigInteger(), nullable=True),
    sa.Column('team_name', sa.String(length=255), nullable=True),
    sa.Column('status_register', sa.Enum('START_REGISTER', 'CREATE_TEAM', 'SEND_NAME_TEAM', 'END_REGISTER', name='status_user_register'), server_default=sa.text("'END_REGISTER'"), nullable=False),
    sa.Column('vip_pass_expiration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_team_name'), 'users', ['team_name'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('characters_user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('talent', sa.Integer(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('MAN', 'WOMAN', name='gender'), nullable=False),
    sa.Column('country', sa.Enum('UKRAINE', 'ARGENTINA', 'BRAZIL', 'FRANCE', 'GERMANY', 'SPAIN', 'ENGLAND', 'ITALY', 'PORTUGAL', 'NETHERLANDS', 'BELGIUM', 'CROATIA', 'URUGUAY', 'MEXICO', 'USA', 'CANADA', 'JAPAN', 'SOUTH_KOREA', 'MOROCCO', 'SENEGAL', 'NIGERIA', name='country'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('training_key', sa.Integer(), server_default='1', nullable=False),
    sa.Column('time_get_member_bonus', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['characters_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_time_payment', sa.DateTime(), nullable=False),
    sa.Column('payment_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('blitz_characters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=True),
    sa.Column('blitz_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('goals_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('count_score', sa.Float(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['blitz_id'], ['blitzs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['blitz_team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('box_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('type_box', sa.Enum('SMALL_BOX', 'MEDIUM_BOX', 'LARGE_BOX', 'NEW_MEMBER_BOX', name='typebox'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['payments.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_box_payment_id'), 'box_payment', ['id'], unique=False)
    op.create_table('character_join_training',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('time_join', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('scores', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('stage', sa.Enum('STAGE_1', 'STAGE_2', 'STAGE_3', 'STAGE_4', 'STAGE_5', 'STAGE_6', 'STAGE_7', 'STAGE_DUEL', 'END_TRAINIG', name='stage'), server_default=sa.text("'STAGE_1'"), nullable=False),
    sa.Column('training_is_end', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_join_training_id'), 'character_join_training', ['id'], unique=False)
    op.create_table('energy_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('amount_energy', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['payments.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_payment_id'), 'energy_payment', ['id'], unique=False)
    op.create_table('money_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=False),
    sa.Column('count_money', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['payments.order_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_money_payment_id'), 'money_payment', ['id'], unique=False)
    op.create_table('reminder_characters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=True),
    sa.Column('character_in_training', sa.Boolean(), nullable=True),
    sa.Column('training_stats', sa.String(length=255), nullable=True),
    sa.Column('time_start_training', sa.DateTime(), nullable=True),
    sa.Column('time_training_seconds', sa.BigInteger(), nullable=True),
    sa.Column('education_reward_date', sa.DateTime(), server_default=sa.text("'1970-01-01 00:00:00'"), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_index(op.f('ix_reminder_characters_id'), 'reminder_characters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_characters_id'), table_name='reminder_characters')
    op.drop_table('reminder_characters')
    op.drop_index(op.f('ix_money_payment_id'), table_name='money_payment')
    op.drop_table('money_payment')
    op.drop_index(op.f('ix_energy_payment_id'), table_name='energy_payment')
    op.drop_table('energy_payment')
    op.drop_index(op.f('ix_character_join_training_id'), table_name='character_join_training')
    op.drop_table('character_join_training')
    op.drop_index(op.f('ix_box_payment_id'), table_name='box_payment')
    op.drop_table('box_payment')
    op.drop_table('blitz_characters')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_team_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_training_timer_id'), table_name='training_timer')
    op.drop_table('training_timer')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_table('blitzs')
    op.drop_table('blitz_team')
    # ### end Alembic commands ###
