"""add transfer

Revision ID: 9347f5f6420b
Revises: 52cc7d950a23
Create Date: 2025-08-18 01:42:13.279670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9347f5f6420b'
down_revision: Union[str, Sequence[str], None] = '52cc7d950a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_characters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('characters_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('transfer_type', sa.Enum('TRANSFER', 'FREE_AGENTS', name='transfertype'), nullable=True),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('characters_id')
    )
    op.create_index(op.f('ix_transfer_characters_id'), 'transfer_characters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_characters_id'), table_name='transfer_characters')
    op.drop_table('transfer_characters')
    # ### end Alembic commands ###
