"""new tables and columns

Revision ID: 95f644625949
Revises: 42c79288a86b
Create Date: 2025-08-13 00:10:28.811156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f644625949'
down_revision: Union[str, Sequence[str], None] = '42c79288a86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('count_play_blitz', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('count_rich_semi_final_blitz', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('count_rich_final_looser_blitz', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('count_rich_final_winner_blitz', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('count_go_to_gym', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'count_go_to_gym')
    op.drop_column('users', 'count_rich_final_winner_blitz')
    op.drop_column('users', 'count_rich_final_looser_blitz')
    op.drop_column('users', 'count_rich_semi_final_blitz')
    op.drop_column('users', 'count_play_blitz')
    # ### end Alembic commands ###
