"""add column point and rem index

Revision ID: ed0c4f953e54
Revises: 4e81d65ea4c3
Create Date: 2025-08-10 18:50:44.212592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0c4f953e54'
down_revision: Union[str, Sequence[str], None] = '4e81d65ea4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('points', sa.BigInteger(), nullable=False))
    op.drop_index(op.f('ix_users_team_name'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_team_name'), 'users', ['team_name'], unique=True)
    op.drop_column('characters', 'points')
    # ### end Alembic commands ###
