"""change type column

Revision ID: ef22b1426fb8
Revises: 95f644625949
Create Date: 2025-08-13 12:24:11.844322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ef22b1426fb8'
down_revision: Union[str, Sequence[str], None] = '95f644625949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('stats')
    op.alter_column('characters', 'power',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'power',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.create_table('stats',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('stat_type', mysql.ENUM('CONDUCT_3_TRAINING', 'PLAY_BLITZ', 'RICH_SEMI_FINAL_BLITZ'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('stats_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
